const fs = require('fs');
const path = require('path');

const directory = __dirname;
const baseUrl = 'https://clashvpns.cloud';

// 1. Get all articles data for related links
let articlesData = [];
try {
    const guidesContent = fs.readFileSync(path.join(directory, 'update_guides.js'), 'utf8');
    const match = guidesContent.match(/const articles = \s*\[([\s\S]*?)\];/);
    if (match) {
        articlesData = eval('[' + match[1] + ']');
    }
} catch (e) {
    console.log('Failed to read update_guides.js for related links.');
}

function walk(dir) {
    let results = [];
    const list = fs.readdirSync(dir);
    list.forEach(function(file) {
        let fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);
        if (stat && stat.isDirectory() && !file.includes('.git') && !file.includes('ready_to_upload')) { 
            // Do not recurse into ready_to_upload to avoid duplicates in sitemap
            // Actually, we probably just want top-level files.
        } else if (stat && !stat.isDirectory()) {
            if(file.endsWith('.html')) {
                results.push(fullPath);
            }
        }
    });
    return results;
}

const htmlFiles = walk(directory);

let sitemapUrls = [];
const today = new Date().toISOString().split('T')[0];

let updatedCount = 0;

htmlFiles.forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    let isModified = false;
    
    // Extract title and description
    let titleMatch = content.match(/<title>(.*?)<\/title>/i);
    let title = titleMatch ? titleMatch[1] : '柳如烟推荐机场';
    
    let descMatch = content.match(/<meta\s+name="description"\s+content="([^"]*)"/i);
    let description = descMatch ? descMatch[1] : '';

    let relativePath = path.relative(directory, file).replace(/\\/g, '/');
    let canonicalUrl = `${baseUrl}/${relativePath}`;
    
    // Add to sitemap
    sitemapUrls.push(`  <url>\n    <loc>${canonicalUrl}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${relativePath === 'index.html' ? 'daily' : 'weekly'}</changefreq>\n    <priority>${relativePath === 'index.html' ? '1.0' : '0.8'}</priority>\n  </url>`);

    // 1. Inject SEO tags if not present
    if (!content.includes('rel="canonical"') && !relativePath.includes('sitemap.html')) {
        const seoTags = `
    <!-- SEO & Spider Web Optimization -->
    <link rel="canonical" href="${canonicalUrl}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="${canonicalUrl}" />
    <meta property="og:site_name" content="柳如烟推荐机场" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />`;
        
        // Some pages might already have og:title, let's just insert these before </head> safely
        // Wait, the new articles generated by script already have some og: tags and JSON-LD.
        // Let's only inject canonical and twitter if they are completely missing.
        let injection = '';
        if (!content.includes('rel="canonical"')) injection += `\n    <link rel="canonical" href="${canonicalUrl}" />`;
        if (!content.includes('twitter:card')) injection += `\n    <meta name="twitter:card" content="summary_large_image" />\n    <meta name="twitter:title" content="${title}" />\n    <meta name="twitter:description" content="${description}" />`;
        
        if (injection) {
            content = content.replace('</head>', `${injection}\n</head>`);
            isModified = true;
        }
    }

    // 2. Inject "Related Reading" spider web at the bottom of the article content if it doesn't have it
    // Skip index, recommend, airport-reviews, sitemap
    const excludeRelated = ['index.html', 'recommend.html', 'airport-reviews.html', 'sitemap.html', 'clash-verge-rev.html', 'shadowrocket.html', 'v2rayn.html', 'stash.html'];
    if (!excludeRelated.includes(relativePath)) {
        if (content.includes('<div class="article-content">') && articlesData.length > 0) {
            // First, remove old spider-web-links if they exist
            const oldSpiderRegex = /<div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid var\(--border-color\);" class="spider-web-links">[\s\S]*?<\/div>\s*<\/div>/g;
            // Wait, the previous block was just one </div> at the end, but the new one has nested divs.
            // Let's use a simpler regex to remove the old block based on its class
            const oldSpiderRegexAlternative = /<div[^>]*class="spider-web-links"[^>]*>[\s\S]*?<\/div>(\s*<\/div>)?/g;
            
            // To be safe, let's just use string manipulation to remove from '<div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid var(--border-color);" class="spider-web-links">'
            // up to the closing </div> before </article>
            let hasOld = content.indexOf('class="spider-web-links"');
            if (hasOld !== -1) {
                // remove the old spider web section
                let startToRemove = content.lastIndexOf('<div', hasOld);
                // find the next </article>
                let articleEnd = content.indexOf('</article>', startToRemove);
                if(articleEnd !== -1) {
                    // Just replace everything from startToRemove to articleEnd - if it's safe.
                    // Actually, let's just remove the block with a regex that matches from <div ... class="spider-web-links"... to the next </div></div> or similar.
                }
            }
            
            // A safer way is to just do it via regex
            content = content.replace(/<div[^>]*class="spider-web-links"[^>]*>[\s\S]*?(?=<\/article>|<\/div>\s*<\/article>)/, '');

            // Ensure we don't duplicate
            if (!content.includes('🔥 热门机场探讨：')) {
                let insertPos = content.indexOf('</div>\n        </article>');
                if (insertPos === -1) insertPos = content.indexOf('</article>');
                
                if (insertPos !== -1) {
                    // Pick 10 random related articles to create a massive spiderweb
                    const shuffled = articlesData.filter(a => a.link !== relativePath).sort(() => 0.5 - Math.random()).slice(0, 10);
                    if (shuffled.length > 0) {
                        const hotArticles = shuffled.slice(0, 5);
                        const relatedArticles = shuffled.slice(5, 10);
                        
                        let listsHtml = '';
                        if (hotArticles.length > 0) {
                            listsHtml += `
                                <div style="flex: 1; min-width: 300px;">
                                    <h3 style="font-size: 1.3rem; margin-bottom: 15px; color: var(--text-main);">🔥 热门机场探讨：</h3>
                                    <ul style="list-style: none; padding-left: 0;">
                                        ${hotArticles.map(item => `<li style="margin-bottom: 10px; font-size: 0.95rem;">👉 <a href="${item.link}" style="color: var(--accent-blue); text-decoration: underline;" title="${item.title}">${item.title}</a></li>`).join('')}
                                    </ul>
                                </div>`;
                        }
                        if (relatedArticles.length > 0) {
                            listsHtml += `
                                <div style="flex: 1; min-width: 300px;">
                                    <h3 style="font-size: 1.3rem; margin-bottom: 15px; color: var(--text-main);">📚 深度阅读与拓展：</h3>
                                    <ul style="list-style: none; padding-left: 0;">
                                        ${relatedArticles.map(item => `<li style="margin-bottom: 10px; font-size: 0.95rem;">👉 <a href="${item.link}" style="color: var(--accent-blue); text-decoration: underline;" title="${item.title}">${item.title}</a></li>`).join('')}
                                    </ul>
                                </div>`;
                        }

                        // Add External Links (Friendly Links)
                        listsHtml += `
                            <div style="flex: 1; min-width: 300px;">
                                <h3 style="font-size: 1.3rem; margin-bottom: 15px; color: var(--text-main);">🌐 推荐资源：</h3>
                                <ul style="list-style: none; padding-left: 0;">
                                    <li style="margin-bottom: 10px; font-size: 0.95rem;">👉 <a href="https://clashwiki.cc/" target="_blank" style="color: var(--accent-blue); text-decoration: underline;" title="机场推荐科学上网教程">机场推荐科学上网教程</a></li>
                                    <li style="margin-bottom: 10px; font-size: 0.95rem;">👉 <a href="https://jichangxuanze.com/" target="_blank" style="color: var(--accent-blue); text-decoration: underline;" title="高性价比机场推荐指南">高性价比机场推荐指南</a></li>
                                </ul>
                            </div>`;

                        const relatedHtml = `
                        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid var(--border-color);" class="spider-web-links">
                            <div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: space-between;">
                                ${listsHtml}
                            </div>
                        </div>\n                `;
                        
                        content = content.slice(0, insertPos) + relatedHtml + content.slice(insertPos);
                        isModified = true;
                    }
                }
            }
        }
    }

    if (isModified) {
        fs.writeFileSync(file, content, 'utf8');
        updatedCount++;
    }
});

// Generate Sitemap
const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapUrls.join('\n')}
</urlset>`;

fs.writeFileSync(path.join(directory, 'sitemap.xml'), sitemapContent, 'utf8');
console.log(`✅ 成功生成 sitemap.xml，共包含 ${sitemapUrls.length} 个 URL 节点。`);
console.log(`✅ 成功在 ${updatedCount} 个 HTML 文件中织入内链蜘蛛网和 SEO 优化标签！`);
