const fs = require('fs');
const path = require('path');

const directory = __dirname;
const baseUrl = 'https://clashvpns.cloud';

// 1. Get all articles data for related links
let articlesData = [];
try {
    const guidesContent = fs.readFileSync(path.join(directory, 'update_guides.js'), 'utf8');
    const match = guidesContent.match(/const articles = \s*\[([\s\S]*?)\];/);
    if (match) {
        articlesData = eval('[' + match[1] + ']');
    }
} catch (e) {
    console.log('Failed to read update_guides.js for related links.');
}

function walk(dir) {
    let results = [];
    const list = fs.readdirSync(dir);
    list.forEach(function(file) {
        let fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);
        if (stat && stat.isDirectory() && !file.includes('.git') && !file.includes('ready_to_upload')) { 
            // Do not recurse into ready_to_upload to avoid duplicates in sitemap
            // Actually, we probably just want top-level files.
        } else if (stat && !stat.isDirectory()) {
            if(file.endsWith('.html')) {
                results.push(fullPath);
            }
        }
    });
    return results;
}

const htmlFiles = walk(directory);

let sitemapUrls = [];
const today = new Date().toISOString().split('T')[0];

let updatedCount = 0;

htmlFiles.forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    let isModified = false;
    
    // Extract title and description
    let titleMatch = content.match(/<title>(.*?)<\/title>/i);
    let title = titleMatch ? titleMatch[1] : '柳如烟推荐机场';
    
    let descMatch = content.match(/<meta\s+name="description"\s+content="([^"]*)"/i);
    let description = descMatch ? descMatch[1] : '';

    let relativePath = path.relative(directory, file).replace(/\\/g, '/');
    let canonicalUrl = `${baseUrl}/${relativePath}`;
    
    // Add to sitemap
    sitemapUrls.push(`  <url>\n    <loc>${canonicalUrl}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${relativePath === 'index.html' ? 'daily' : 'weekly'}</changefreq>\n    <priority>${relativePath === 'index.html' ? '1.0' : '0.8'}</priority>\n  </url>`);

    // 1. Inject SEO tags if not present
    if (!content.includes('rel="canonical"') && !relativePath.includes('sitemap.html')) {
        const seoTags = `
    <!-- SEO & Spider Web Optimization -->
    <link rel="canonical" href="${canonicalUrl}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="${canonicalUrl}" />
    <meta property="og:site_name" content="柳如烟推荐机场" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />`;
        
        // Some pages might already have og:title, let's just insert these before </head> safely
        // Wait, the new articles generated by script already have some og: tags and JSON-LD.
        // Let's only inject canonical and twitter if they are completely missing.
        let injection = '';
        if (!content.includes('rel="canonical"')) injection += `\n    <link rel="canonical" href="${canonicalUrl}" />`;
        if (!content.includes('twitter:card')) injection += `\n    <meta name="twitter:card" content="summary_large_image" />\n    <meta name="twitter:title" content="${title}" />\n    <meta name="twitter:description" content="${description}" />`;
        
        if (injection) {
            content = content.replace('</head>', `${injection}\n</head>`);
            isModified = true;
        }
    }

    // 2. Inject "Related Reading" spider web at the bottom of the article content if it doesn't have it
    // Skip index, recommend, airport-reviews, sitemap
    const excludeRelated = ['index.html', 'recommend.html', 'airport-reviews.html', 'sitemap.html', 'clash-verge-rev.html', 'shadowrocket.html', 'v2rayn.html', 'stash.html'];
    if (!excludeRelated.includes(relativePath)) {
        if (content.includes('<div class="article-content">') && !content.includes('相关阅读推荐：') && articlesData.length > 0) {
            // Find a place to insert it. Usually right before </div></article>
            let insertPos = content.indexOf('</div>\n        </article>');
            if (insertPos === -1) insertPos = content.indexOf('</article>');
            
            if (insertPos !== -1) {
                // Pick 4 random related articles
                const shuffled = articlesData.filter(a => a.link !== relativePath).sort(() => 0.5 - Math.random()).slice(0, 4);
                if (shuffled.length > 0) {
                    const relatedHtml = `
                    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid var(--border-color);" class="spider-web-links">
                        <h3 style="font-size: 1.3rem; margin-bottom: 15px; color: var(--text-main);">相关阅读推荐：</h3>
                        <ul style="list-style: none; padding-left: 0;">
                            ${shuffled.map(item => `<li style="margin-bottom: 10px;">👉 <a href="${item.link}" style="color: var(--accent-blue); text-decoration: underline;">${item.title}</a></li>`).join('')}
                        </ul>
                    </div>\n                `;
                    
                    content = content.slice(0, insertPos) + relatedHtml + content.slice(insertPos);
                    isModified = true;
                }
            }
        }
    }

    if (isModified) {
        fs.writeFileSync(file, content, 'utf8');
        updatedCount++;
    }
});

// Generate Sitemap
const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapUrls.join('\n')}
</urlset>`;

fs.writeFileSync(path.join(directory, 'sitemap.xml'), sitemapContent, 'utf8');
console.log(`✅ 成功生成 sitemap.xml，共包含 ${sitemapUrls.length} 个 URL 节点。`);
console.log(`✅ 成功在 ${updatedCount} 个 HTML 文件中织入内链蜘蛛网和 SEO 优化标签！`);
